# Generated by Django 5.1.6 on 2025-08-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Nacional', 'Nacional'), ('Internacional', 'Internacional')], max_length=20)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['precio'],
            },
        ),
    ]
